CREATE DATABASE ALUNOS;
USE ALUNOS;

CREATE TABLE ALUNO(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    ESCOLA TEXT NOT NULL,
    CURSO TEXT NOT NULL
);

insert into ALUNO (NOME, ESCOLA,CURSO) values(":PNAME", ":PSCHOOL", ":PCOURSE");
UPDATE ALUNO SET NOME = ':PNOME', ESCOLA = ':PESCOLA', CURSO = ':PCURSO' WHERE ID = ':ID';
UPDATE ALUNO SET NOME = 'Joao', ESCOLA = 'HM', CURSO = 'ELETRICA' WHERE ID = 1;
DELETE FROM ALUNO WHERE ID = ':ID';
select * from ALUNO;